[package]
name = "use_prompt"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
serde = "1"
serde_json = "1.0.132"
swc_core = { version = "0.101.*", features = [
    "ecma_plugin_transform",
    "ecma_codegen",
    "ecma_parser",
    "typescript",
] }
wasix = "0.12.21"
